name = "AugmeconMethods"
uuid = "78705326-e6c4-40ef-a028-b98696ee36e2"
authors = ["Josa Ferreira"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
